### PR TITLE
New validateDomainSuffix addition

### PR DESCRIPTION
**Pull request by knil-maloon**
New changes we discussed. I tested them and it works well.

### CODE REVIEW

**Review by mmcev106 — CHANGES_REQUESTED** [review]
The general idea looks good.  In our chat with Alex I mentioned supporting additional common s3 domain suffixes, and implementing this as a `validatateS3Url()`, which I believe would allow me to ignore false positives in the scanner).  What are your thoughts on those things?

**Comment by knil-maloon** [comment]
Sorry! Somehow I missed that line in the conversation!
I just changed the name to _validateS3Url_. It will be great not getting those errors on psalm. Thanks!

**Comment by mmcev106** [comment]
@knil-maloon, I think a higher level of attention to detail might be required here.  No worries if you need to take a break before you'll have the right energy to really think about what is being requested.  Specifically, I talked about supporting additional common s3 domain suffixes twice now (the first time on slack), and that comment seems to have been missed both times.  Also, simply changing the name of the function doesn't make sense.  If it is going to validate s3 urls, then it has to actually validate s3 urls.  As-in, the urls it validates against should be built into the function, not passed in.

**Comment by knil-maloon** [comment]
Added changes we talked about and a TODO as my personal reminder as well.

**Review by mmcev106 — APPROVED** [review]
This makes sense to me, and should overlap nicely with the framework implementation 'm working on so that the security scanner considers it safe.  Thank you!

**Pull request merged**
